---

- name: Get Master IP
  set_fact:
    master: "{{ groups.master[0] }}"

- name: print Master IP
  debug: msg="Master IP  {{ groups.master[0] }}"
  
- name: print play_hosts
  debug: msg="{{play_hosts}}"

- name: print groups
  debug: msg="{{groups}}"

- name: print Master hostvars
  debug: msg="Master Hostvars {{ hostvars['master'] }}"

- name: SET 2
  set_fact:
    info_temp: "{{ hostvars['master']['master_status'] }}"

- name: show
  debug: var=info_temp['Position']
